cmake_minimum_required(VERSION 3.20)
project(programming_lab_assignments LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(4.11a 4.11a.cpp)
add_executable(4.2 4.2.cpp)
add_executable(4.26 4.26.cpp)
add_executable(4.28 4.28.cpp)
add_executable(4.7 4.7.cpp)
add_executable(5.1a 5.1a.cpp)
add_executable(5.15b 5.15b.cpp)
add_executable(5.22 5.22.cpp)
add_executable(5.25a 5.25a.cpp)
add_executable(5.26g 5.26g.cpp)
add_executable(5.27i 5.27i.cpp)
add_executable(5.31 5.31.cpp)
add_executable(5.36a 5.36a.cpp)
add_executable(5.41a 5.41a.cpp)
